// Generated by CoffeeScript 1.4.0
(function() {
  var Mixin;

  Mixin = (function() {

    function Mixin() {}

    Mixin.mixinTo = function(klazz) {
      this.extend(klazz, this.addTheseToClass);
      return this.extend(klazz.prototype, this.addTheseToInstance);
    };

    Mixin.extend = function(target, mixin) {
      var key, value, _results;
      _results = [];
      for (key in mixin) {
        value = mixin[key];
        _results.push(target[key] = value);
      }
      return _results;
    };

    return Mixin;

  })();

  module.exports = Mixin;

}).call(this);
