// Generated by CoffeeScript 1.4.0
(function() {
  var Mixin;

  Mixin = (function() {

    function Mixin() {}

    /*
      #   @@mixinTo
      #   Inject the class and instance (methods and attributes) of this mixin into the target klazz
    */


    Mixin.mixinTo = function(klazz) {
      this.extend(klazz, this.includedAddTheseToClass);
      this.extend(klazz.prototype, this.includedAddTheseToInstance);
      this.extend(klazz, this.addTheseToClass);
      return this.extend(klazz.prototype, this.addTheseToInstance);
    };

    /*
      #   @@include
      #   Allows a mixin to include other mixins
    */


    Mixin.include = function(OtherMixin) {
      this.includedAddTheseToClass || (this.includedAddTheseToClass = {});
      this.includedAddTheseToInstance || (this.includedAddTheseToInstance = {});
      if (OtherMixin.addTheseToClass != null) {
        this.extend(this.includedAddTheseToClass, OtherMixin.addTheseToClass);
      }
      if (OtherMixin.addTheseToInstance != null) {
        return this.extend(this.includedAddTheseToInstance, OtherMixin.addTheseToInstance);
      }
    };

    Mixin.extend = function(target, mixin) {
      var key, value, _results;
      _results = [];
      for (key in mixin) {
        value = mixin[key];
        _results.push(target[key] = value);
      }
      return _results;
    };

    return Mixin;

  })();

  module.exports = Mixin;

}).call(this);
